import GUI.functions as f

RESIZE_X = False
RESIZE_Y = False
APP_TITLE = "C Compiler"
MAIN_TITLE = "File Manager System for C"
MAIN_ICON_PATH = ".\DATA\icons\main.ico"
SETTING_ICON_PATH = r''
EDITPAGE_ICON_PATH = r''
INITIAL_FOLDER_PATH = f.get_init_path()
LOG_FOLDER_PATH = f.get_log_path()

# COLORS
MAIN_CANVAS_BG = "#fff"
FOLDER_CANVAS_BG = "#777777"
FOLDER_BUTTON_CANVAS_BG = FOLDER_CANVAS_BG
DETAIL_CANVAS_BG = "#222222"
TABLE_CANVAS_BG = "#111111"
SETTING_CANVAS_BG = "#777777"
SETTING_CANVAS_ROWS_BG = "#333333"
EDIT_CANVAS_BG = "#777777"
TOOLS_FRAME_BG = "#333333"
TEXT_FRAME_BG = "#666666"

START_FRAME_BG = "#333333"
TIP_FG = "#000"
TIP_BG = "#fff"

F_FOLDER_BG = "#555555"
F_TABLE_BG = "#333333"
F_DETAIL_BG = "#999999"
LABEL_BG = "#fff"
LABEL_FG = "#000"
INFO_LABEL_FG = "#777777"
BUTTON_BG = "#fff"
BUTTON_FG = "#000"

# FONTS
TITLE_FONT = 'times 22 bold'
TITLE_2_FONT = 'times 18 bold'
PARAG_FONT = 'times 12 bold'
INFO_FONT = 'times 9 italic'